turtlebot2: #namespace

    n_actions: 3 # We have 3 actions, Forwards,TurnLeft,TurnRight
    n_observations: 5 # We have 5 different observations

    speed_step: 0.5 # Time to wait in the reset phases

    linear_forward_speed: 0.5 # Spawned for ging fowards
    linear_turn_speed: 0.1 # Lienare speed when turning
    angular_speed: 0.8 # 0.3 Angular speed when turning Left or Right
    init_linear_forward_speed: 0.0 # Initial linear speed in which we start each episode
    init_linear_turn_speed: 0.0 # Initial angular speed in shich we start each episode
    
    new_ranges: 5 # How many laser readings we jump in each observation reading, the bigger the less laser resolution
    min_range: 0.2 # 0.5 Minimum meters below wich we consider we have crashed
    max_laser_value: 6 # Value considered Ok, no wall
    min_laser_value: 0 # Value considered there is an obstacle or crashed
    
    number_of_sectors: 3 # How many sectors we have
  
    middle_range: 1.0 # Minimum meters below wich we consider we have crashed
    danger_laser_value: 2 # Value considered Ok, no wall
    middle_laser_value: 1 # Middle value
    safe_laser_value: 0 # Value considered there is an obstacle or crashed
    
    forwards_reward: 0 # 5 Points Given to go forwards
    turn_reward: 0 # 4 Points Given to turn as action
    end_episode_points: 2 # 200 Points given when ending an episode
    

